[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

# Enable Next.js runtime for Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

# API routes as Netlify Functions
[functions]
  directory = ".netlify/functions"

# Headers for security and CORS
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Redirect all API calls to Next.js API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nextjs/:splat"
  status = 200

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["client"]}

# Environment variables (you'll need to set these in Netlify dashboard)
# NEXT_PUBLIC_SUPABASE_URL
# NEXT_PUBLIC_SUPABASE_ANON_KEY
# SUPABASE_SERVICE_ROLE_KEY
# STRIPE_SECRET_KEY
# STRIPE_PUBLISHABLE_KEY
# STRIPE_WEBHOOK_SECRET
# OPENAI_API_KEY

# Development settings
[dev]
  command = "npm run dev"
  port = 3000
  publish = ".next" 