[build]
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

# Enable Next.js runtime for Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Headers for security and CORS
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Handle client-side routing (let Next.js plugin handle routing)
# No redirects needed when using @netlify/plugin-nextjs

# Environment variables (you'll need to set these in Netlify dashboard)
# NEXT_PUBLIC_SUPABASE_URL
# NEXT_PUBLIC_SUPABASE_ANON_KEY
# SUPABASE_SERVICE_ROLE_KEY
# STRIPE_SECRET_KEY
# STRIPE_PUBLISHABLE_KEY
# STRIPE_WEBHOOK_SECRET
# OPENAI_API_KEY

# Development settings
[dev]
  command = "npm run dev"
  port = 3000 